package baspig.apis.utils.util;

public enum ParticleVelocityType {
    CUSTOM,
    RANDOM,
    UPWARD,
    DOWNWARD,
    EASTWARD,
    WESTWARD,
    NORTHWARD,
    SOUTHWARD,
    UPWARD_SLOW,
    DOWNWARD_SLOW,
    EASTWARD_SLOW,
    WESTWARD_SLOW,
    NORTHWARD_SLOW,
    SOUTHWARD_SLOW,
    DOWNWARD_CUSTOM_VELOCITY,
    UPWARD_CUSTOM_VELOCITY,
    EASTWARD_CUSTOM_VELOCITY,
    WESTWARD_CUSTOM_VELOCITY,
    NORTHWARD_CUSTOM_VELOCITY,
    SOUTHWARD_CUSTOM_VELOCITY

}
